#!/bin/sh

### BEGIN INIT INFO
# /etc/init.d/mycs
# Description:		My Service for Cubie
# 			http://mycubieserv.blogspot.com/
#			https://github.com/mycubieserv/Service-Scripte
### END INIT INFO

. /lib/lsb/init-functions


NAME="My Cubie Service"
DESC="My Cubie Service"
FILE_BACKUP=/home/user/sata/_backup_/backup.tar.gz
BACKUP_FILELIST=/home/user/sata/_backup_/backupfiles.lst
CRONTAB_FILE=/home/user/sata/_backup_/crontab.txt
STATUS_CMD="/etc/init.d/mybackup bck-status"
FULL_UPGRADE_CMD="/etc/init.d/mybackup full-upgrade"
USER_PASS=root:****


# Carry out specific functions when asked to by the system
case "$1" in
        up-inst-all)
                log_action_msg "Sources list update..."
			echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list

		$FULL_UPGRADE_CMD

                log_action_msg "Starting install all packages..."
			wget http://www.webmin.com/jcameron-key.asc 
			apt-key add jcameron-key.asc

			apt-get install memtester curl samba webmin python-pip mpd mpc transmission-daemon motion libv4l-dev libv4l-0 libjpeg8-dev imagemagick uvcdynctrl -y --force-yes
			pip install --upgrade setuptools 
			pip install d2pi

                log_action_msg "Install packages comlete!"
                ;;
        tune-all)
                log_action_msg "Starting Tune..."
			cubie-config
                log_action_msg "VNC-user password:"
			x11vnc -storepasswd
                log_action_msg "ROOT-user password:"
			passwd root
                log_action_msg "CUBIE-user password:"
			passwd cubie

			service mpd stop
			mpd --create-db
			service mpd start

			ln -sf /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3

                log_action_msg "Tune comlete!"
		$STATUS_CMD
                ;;
        backup)
                log_action_msg "Prepare backup files..."
			# crontab -u $USER_PASS -l > $CRONTAB_FILE
			rm -f $BACKUP_FILELIST
			rm -rf /tmp/*

			ls /var/lib/transmission-daemon/info/torrents/ > /tmp/bck_torrents
			ls /var/lib/transmission-daemon/info/resume/ > /tmp/bck_resume
			ls /var/lib/transmission-daemon/info/blocklists/ > /tmp/bck_blocklists
			ls /var/lib/mpd/ > /tmp/bck_mpd
			ls /var/lib/mpd/playlists/ > /tmp/bck_playlists 
			ls \home\cubie\Desktop\ > /tmp/bck_desktop_cubie
			ls \home\cubie\.mozilla\ > /tmp/bck_mozilla_cubie
			ls \root\.mozilla\ > /tmp/bck_mozilla_root	
			ls \root\Desktop\ > /tmp/bck_desktop_root

			touch $BACKUP_FILELIST
			cat /tmp/bck_torrents /tmp/bck_resume /tmp/bck_blocklists /tmp/bck_mpd /tmp/bck_playlists /tmp/bck_mozilla_cubie /tmp/bck_desktop_cubie /tmp/bck_mozilla_root /tmp/bck_desktop_root > $BACKUP_FILELIST &
			rm -rf /tmp/*

                log_action_msg "Starting backup files..."
			tar -zcvpf $FILE_BACKUP --directory / --files-from $BACKUP_FILELIST 

                log_action_msg "Backup files comlete!"
		$STATUS_CMD
                ;;
        restore)
                log_action_msg "Starting restore files..."
			/etc/init.d/transmission-daemon stop
			service mpd stop

			tar -zxvpf $FILE_BACKUP --directory /
			# crontab -u $USER_PASS $CRONTAB_FILE

			/etc/init.d/transmission-daemon start
			service mpd start

                log_action_msg "Restore files comlete!"
		$STATUS_CMD
                ;;
        bck-status)
                log_action_msg "Status:"
                log_action_msg "   >>> File Systems:"
			echo df -h

		sleep 1
                log_action_msg "   >>> Backup archive:"
			echo du -h $FILE_BACKUP

		sleep 2
                log_action_msg "   >>> Archive listing:"
			echo tar -tvf $FILE_BACKUP

		# sleep 3
                # log_action_msg "   >>> Cron:"
		# 	echo crontab -u $USER_PASS -l 
                ;;
        apt-clear)
                log_action_msg "Starting APT-clear..."
			dpkg --clear-avail
			apt-get clean -y -f --force-yes

			rm /var/lib/dpkg/available -vrf
			rm /var/lib/dpkg/status -vrf

			rm /var/lib/apt/lists/partial/* -vrf 
			rm /var/lib/apt/lists/* -vrf 
			mkdir -p /var/lib/apt/lists/partial 

			rm /var/cache/apt/archives/partial/* -vrf 
			rm /var/cache/apt/archives* -vrf 
			mkdir -p /var/cache/apt/archives/partial 

			dpkg --configure -a

                log_action_msg "APT-clear comlete!"
			$FULL_UPGRADE_CMD
                ;;
        full-upgrade)
                log_action_msg "Starting full upgrade..."
			apt-get update -y -f --force-yes
			apt-get upgrade -y -f --force-yes 
			apt-get dist-upgrade -y -f --force-yes 
			apt-get update -y --force-yes

                log_action_msg "Upgrade packages comlete!"
                ;;
        shutdown)
                log_action_msg "Shutdown system now..."
			shutdown -h now
                ;;
        *)
                log_action_msg "Usage: $0 {up-inst-all|tune-all|backup|restore|bck-status|apt-clear|full-upgrade|shutdown}"
                exit 1
                ;;
esac
exit 0
